### ISSUE TITLE
Provide public binaries and packages

### ISSUE THREAD

**Issue by siddharthist** [hashicorp/vault-ssh-helper#4] opened 2016-02-10 08:31 UTC
Other Hashicorp tools, like Vault and Vagrant provide pre-built archived releases for ease of installation. This eases automated installs as well. This should be built into this project's CI/CD build.

**Comment by sethvargo** [comment] 2016-02-10 11:23
Duplicate of https://github.com/hashicorp/vault-ssh-helper/issues/2. They are on releases.hashicorp.com.

**Closed by sethvargo** 2016-02-10 11:23 UTC

**Comment by siddharthist** [comment] 2016-02-10 18:09
@sethvargo Perhaps a link should be added to the README under installation?

**Comment by vishalnayak** [comment] 2016-02-10 19:20
@siddharthist: That's a good suggestion.
Done!
