### ISSUE TITLE
Invalid (empty) CIDR address

### ISSUE THREAD

**Issue by siddharthist** [hashicorp/vault-ssh-helper#10] opened 2016-02-19 07:09 UTC
Hi there, I got the following error with vault-ssh-helper recently:
```
*** Fri Feb 19 07:03:32 2016
2016/02/19 07:03:32 [INFO] Using SSH Mount point: ssh
2016/02/19 07:03:32 [ERROR]: invalid CIDR address:
```
Verification works with `-verify`. 

Here's the relevant part of the sshd log:
```
Feb 19 07:03:32 ip-10-1-3-48.us-west-2.compute.internal sshd[22092]: pam_exec(sshd:auth): /usr/local/bin/vault-ssh-helper failed: exit code 1
Feb 19 07:03:32 ip-10-1-3-48.us-west-2.compute.internal sshd[22092]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=c135h012.wless.reed.edu  user=centos
Feb 19 07:03:34 ip-10-1-3-48.us-west-2.compute.internal sshd[22089]: error: PAM: Authentication failure for centos from c135h012.wless.reed.edu
```

Could you help me understand what's happening here?

I assume the error is from here: https://github.com/hashicorp/vault-ssh-helper/blob/master/main.go#L107

I'm going to try leaving off the `cidr_list` option and I'll report back if that works.

**Comment by siddharthist** [comment] 2016-02-19 10:00
After removing the `cidr_list` variable, I get the following error when trying to create OTPs:
```
failed: [lb-control-03] => (item=lb-control-03) => {"changed": true, "cmd": ["vault", "ssh", "-tls-skip-verify", "-no-exec", "-format=json", "-role=otp_key_role", "centos@52.35.157.114"], "delta": "0:00:00.073285", "end": "2016-02-19 09:58:47.642192", "item": "lb-control-03", "rc": 1, "start": "2016-02-19 09:58:47.568907", "warnings": []}
stderr: Error getting key for SSH session:Error making API request.

URL: PUT https://lb-control-02.node.consul:8200/v1/ssh/creds/otp_key_role
Code: 400. Errors:

* Error validating IP: IP does not belong to role
```
Any ideas? Thanks in advance!

**Comment by vishalnayak** [comment] 2016-02-23 15:26
@siddharthist The error "invalid CIDR address" is not coming from either the Vault code or the vault-ssh-helper code. I am guessing that this could be a problem with Go's ParseCIDR method.

You can check if the CIDR block you are providing to the SSH role in Vault is getting parsed properly (maybe by writing a simple test code).

**Comment by jefferai** [comment] 2016-02-23 15:33
Any chance you can provide us with the parameters you used to
configure the role?

**Comment by siddharthist** [comment] 2016-02-23 18:33
@jefferai [Here's the vault role I'm using](https://github.com/CiscoCloud/mantl/tree/feature/vault-otp/roles/vault). Thanks for your help!

**Comment by jefferai** [comment] 2016-02-23 19:20
@vishalnayak From https://github.com/CiscoCloud/mantl/blob/feature/vault-otp/roles/vault/tasks/otp.yml it looks like `cidr_list` isn't being set so it *ought* to allow all IPs, or did this behavior change somewhere along the way?

@siddharthist Just to check, you're running with IPv4, right?

**Comment by siddharthist** [comment] 2016-02-23 19:26
@jefferai Sorry, I should've been more clear in my above comments. I disabled the CIDR list after running into my original problem, and after doing so, ran into the error in my second comment.

**Comment by siddharthist** [comment] 2016-02-23 19:27
Yes, these are all IPv4 addresses being dealt with AFAICT.

**Comment by jefferai** [comment] 2016-02-23 19:32
@siddharthist I think the second error is indeed a bug.

**Comment by vishalnayak** [comment] 2016-02-23 20:01
@siddharthist 
The problem you ran into after removing the `cidr_list` is a documentation bug. If `cidr_list` is not specified, the role will default to no IP address.

Before requesting a credential against a particular role, if you want credentials to be created for any IP address, then the role can be configured as a zero-address role.

Please see `vault path-help ssh` and `vault path-help ssh/config/zeroaddress` for more information.

**Comment by siddharthist** [comment] 2016-02-23 20:09
Yeah, [on this page](https://www.vaultproject.io/docs/secrets/ssh/index.html), it says

>  cidr_list optional for both types (String) Comma separated list of CIDR blocks for which the role is applicable for. CIDR blocks can belong to more than one role. Defaults to the zero address (0.0.0.0/0).

**Comment by vishalnayak** [comment] 2016-02-23 20:12
@siddharthist That's the documentation bug :)
`cidr_list` was initially getting defaulted to zero address, but later on, it was removed.
If `cidr_list` is empty, it simply means, no IPs.
It doesn't throw any error because, the role can be a ZeroAddress role still.

**Comment by siddharthist** [comment] 2016-02-23 20:15
I'll open an issue against Vault.

**Comment by siddharthist** [comment] 2016-02-24 04:30
Unfortunately, after explicitly passing `cidr_list=0.0.0.0/0` when writing `ssh/roles/otp_key_role`, I get the same error:
```
[centos@ip-10-1-3-95 ~]$ cat /tmp/vaultssh.log 
*** Wed Feb 24 04:28:15 2016
2016/02/24 04:28:15 [INFO] Using SSH Mount point: ssh
2016/02/24 04:28:15 [ERROR]: invalid CIDR address:          
[centos@ip-10-1-3-95 ~]$ cat /etc/vault/ssh-helper.hcl 
vault_addr = "https://lb-control-03.node.consul:8200"
ssh_mount_point = "ssh"
tls_skip_verify = true
```

**Comment by vishalnayak** [comment] 2016-02-24 05:00
@siddharthist 
>Error validating IP: IP does not belong to role
This problem is now certainly resolved. You are now able to generate an OTP.
When this OTP is presented to the PAM module for authentication, you are facing an error.

Looking at the code, I feel that there is a chance that IP address against which the OTP is generated, is not matching the host's network interface(s). When this happens vault-ssh-helper will try to find the address in the allowed_cidr_list.
See `allowed_cidr_list` in https://github.com/hashicorp/vault-ssh-helper.

I looked at https://github.com/CiscoCloud/mantl/blob/feature/vault-otp/roles/vault/tasks/otp.yml.

You can attempt to do the following:
First, **only for now**, add `allowed_cidr_list=0.0.0.0/0` as a parameter to vault-ssh-helper.
Here: https://github.com/CiscoCloud/mantl/blob/feature/vault-otp/roles/vault/tasks/otp.yml#L90

Second, PAM auth flow is sequential and hence you need to swap these two lines.
> 'auth       optional     pam_unix.so not_s....
> 'auth       sufficient   pam_exec.so quiet ex....

Let me know if this takes you any further.

**Comment by siddharthist** [comment] 2016-02-24 06:33
@vishalnayak Those lines are in reverse order because they are each placed after the first line of the file, so they end up in order after all:
```
#%PAM-1.0
auth       sufficient   pam_exec.so quiet expose_authtok log=/tmp/vaultssh.log /usr/local/bin/vault-ssh-helper -config-file=/etc/vault/ssh-helper.hcl
auth       optional     pam_unix.so not_set_pass use_first_pass nodelay
...
```
After adding your suggested line to `/etc/pam.d/sshd`:
```
auth       sufficient   pam_exec.so quiet expose_authtok log=/tmp/vaultssh.log /usr/local/bin/vault-ssh-helper -config-file=/etc/vault/ssh-helper.hcl allowed_cidr_list=0.0.0.0/0
```
and attempting to log in with a fresh OTP, `sshd` has the following log:
```
Feb 24 06:29:23 ip-10-1-3-247.us-west-2.compute.internal sshd[865]: pam_exec(sshd:auth): /usr/local/bin/vault-ssh-helper failed: exit code 1
Feb 24 06:29:23 ip-10-1-3-247.us-west-2.compute.internal sshd[865]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=c135h012.wless.reed.edu  user=centos
Feb 24 06:29:24 ip-10-1-3-247.us-west-2.compute.internal sshd[863]: error: PAM: Authentication failure for centos from c135h012.wless.reed.edu
Feb 24 06:29:26 ip-10-1-3-247.us-west-2.compute.internal sshd[863]: Connection closed by 134.10.135.12 [preauth]
Feb 24 06:29:28 ip-10-1-3-247.us-west-2.compute.internal sshd[989]: Accepted publickey for centos from 134.10.135.12 port 46802 ssh2: RSA [...]
```
and vault-ssh-helper has this one to match:
```
*** Wed Feb 24 06:29:22 2016
2016/02/24 06:29:22 [INFO] Using SSH Mount point: ssh
2016/02/24 06:29:23 [ERROR]: invalid CIDR address: 
```
This is still having manually set `cidr_list=0.0.0.0/0`. It looks to me like PAM is failing because `vault-ssh-helper` is failing, not because of any other configuration problem.

**Comment by vishalnayak** [comment] 2016-02-24 15:18
@siddharthist I sorry for having you pass 'allowed_cidr_list' as a parameter to `vault-ssh-helper`.
It should be supplied via config file:
> allowed_cidr_list="0.0.0.0/0"

I found the place where this is faulting and was able to reproduce this issue.
I'll add the check to return a meaningful error message instead of "invalid CIDR address".

Hope this helps!

**Comment by vishalnayak** [comment] 2016-02-24 15:42
Fixed by #15

**Closed by vishalnayak** 2016-02-24 15:42 UTC

**Comment by vishalnayak** [comment] 2016-02-24 16:31
@siddharthist 
In case you download the code from `master` now, please note that in order to make the UX consistent with Vault, the `config-file` parameter is renamed to `config` and `verify` is renamed to `verify-only`.

And a `dev` mode option is provided.
Only in `dev` mode, `vault-ssh-helper` will communicate with Vault in non-TLS mode.

Just FYI.

**Comment by siddharthist** [comment] 2016-02-24 22:29
How do you feel about another release since the API is broken by those changes?

**Comment by vishalnayak** [comment] 2016-02-24 23:55
@siddharthist Certainly! Anytime soon.

**Comment by Fastersush** [comment] 2019-02-15 06:09
2019/02/15 11:36:17 [ERROR]: parse x.x.x.x:8200: first path segment in URL cannot contain colon
getting this error when i try to ssh on client node

below is my config file on client 

vault_addr = "x.x.x.x:8200"
ssh_mount_point = "ssh"
tls_skip_verify = false
allowed_roles = "*"

please here to resolve this

**Comment by Fastersush** [comment] 2019-02-15 06:11
@vishalnayak , please your quick help is really appreciated
